#!/usr/bin/env python3
"""Build sustained background demand by repeating the calibrated TOPIS pattern."""

from __future__ import annotations

import argparse
import copy
import hashlib
import math
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_INPUT = PROJECT_ROOT / "data_prepared/demand/background_routes_am_imputed_a17_a19.rou.xml"
DEFAULT_OUTPUT = PROJECT_ROOT / "data_prepared/demand/background_routes_am_imputed_a17_a19_warm0p15_sustain0p05_seed002_sustained_3600.rou.xml"
DEFAULT_WARMUP_SCALE = 0.15
DEFAULT_SUSTAIN_SCALE = 0.05
DEFAULT_SAMPLING_SEED = "sustained_calibration_seed_002"


class SustainedDemandError(RuntimeError):
    """Expected sustained demand generation failure."""


def rel(path: Path) -> str:
    return path.resolve().relative_to(PROJECT_ROOT).as_posix()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Repeat a calibrated 600s route pattern to build sustained demand.")
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--base-input", type=Path, default=None)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--period-sec", type=float, default=600.0)
    parser.add_argument("--duration-sec", type=float, default=3600.0)
    parser.add_argument("--warmup-scale", type=float, default=DEFAULT_WARMUP_SCALE)
    parser.add_argument("--sustain-scale", type=float, default=DEFAULT_SUSTAIN_SCALE)
    parser.add_argument("--sampling-seed", default=DEFAULT_SAMPLING_SEED)
    return parser.parse_args()


def vehicle_depart(vehicle: ET.Element) -> float:
    value = vehicle.get("depart")
    if value in {"", None}:
        raise SustainedDemandError(f"vehicle missing depart: {vehicle.get('id', '')}")
    return float(value)


def vehicle_sort_key(vehicle: ET.Element) -> tuple[float, str]:
    return vehicle_depart(vehicle), vehicle.get("id", "")


def deterministic_vehicle_hash(vehicle_id: str, scale: float, seed: str) -> str:
    label = str(scale).replace(".", "p")
    return hashlib.sha256(f"{seed}:{label}:{vehicle_id}".encode("utf-8")).hexdigest()


def select_scaled_vehicles(vehicles: list[ET.Element], scale: float, seed: str) -> list[ET.Element]:
    if scale <= 0 or scale > 1:
        raise SustainedDemandError("scale must be in (0, 1]")
    keep_count = round(len(vehicles) * scale)
    ranked = sorted(
        vehicles,
        key=lambda vehicle: (
            deterministic_vehicle_hash(vehicle.get("id", ""), scale, seed),
            vehicle_sort_key(vehicle),
        ),
    )
    selected = ranked[:keep_count]
    return sorted(selected, key=vehicle_sort_key)


def build_sustained(
    input_path: Path,
    output_path: Path,
    period_sec: float,
    duration_sec: float,
    warmup_scale: float | None = None,
    sustain_scale: float | None = None,
    sampling_seed: str = "step10_scale_calibration_v1",
) -> dict[str, Any]:
    if period_sec <= 0:
        raise SustainedDemandError("period-sec must be positive")
    if duration_sec <= 0:
        raise SustainedDemandError("duration-sec must be positive")
    if (warmup_scale is None) != (sustain_scale is None):
        raise SustainedDemandError("warmup-scale and sustain-scale must be provided together")
    root = ET.parse(input_path).getroot()
    children = list(root)
    vehicles = [child for child in children if child.tag == "vehicle"]
    if not vehicles:
        raise SustainedDemandError(f"input has no vehicles: {rel(input_path)}")
    cycles = int(math.ceil(duration_sec / period_sec))
    output_root = ET.Element(root.tag, root.attrib)
    output_root.append(
        ET.Comment(
            "sustained demand generated by repeating "
            f"{rel(input_path)} period_sec={period_sec:g} duration_sec={duration_sec:g} cycles={cycles}"
        )
    )
    for child in children:
        if child.tag != "vehicle":
            output_root.append(copy.deepcopy(child))
    if warmup_scale is None:
        vehicles_by_cycle = {cycle: vehicles for cycle in range(cycles)}
    else:
        warmup_vehicles = select_scaled_vehicles(vehicles, warmup_scale, sampling_seed)
        sustain_vehicles = select_scaled_vehicles(vehicles, sustain_scale or 0.0, sampling_seed)
        vehicles_by_cycle = {0: warmup_vehicles, **{cycle: sustain_vehicles for cycle in range(1, cycles)}}
    seen_ids: set[str] = set()
    depart_values: list[float] = []
    vehicle_counts_by_cycle: list[int] = []
    for cycle in range(cycles):
        offset = cycle * period_sec
        cycle_count = 0
        for vehicle in vehicles_by_cycle[cycle]:
            cloned = copy.deepcopy(vehicle)
            old_id = cloned.get("id", "")
            if not old_id:
                raise SustainedDemandError("vehicle missing id")
            new_id = f"{old_id}_sust{cycle:03d}"
            if new_id in seen_ids:
                raise SustainedDemandError(f"duplicate vehicle id: {new_id}")
            seen_ids.add(new_id)
            depart = vehicle_depart(cloned) + offset
            if depart >= duration_sec:
                continue
            cloned.set("id", new_id)
            cloned.set("depart", f"{depart:.2f}")
            depart_values.append(depart)
            output_root.append(cloned)
            cycle_count += 1
        vehicle_counts_by_cycle.append(cycle_count)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    ET.ElementTree(output_root).write(output_path, encoding="utf-8", xml_declaration=True)
    return {
        "input": rel(input_path),
        "output": rel(output_path),
        "base_vehicle_count": len(vehicles),
        "cycles": cycles,
        "vehicle_count": len(depart_values),
        "vehicle_counts_by_cycle": vehicle_counts_by_cycle,
        "min_depart": min(depart_values),
        "max_depart": max(depart_values),
        "period_sec": period_sec,
        "duration_sec": duration_sec,
        "warmup_scale": warmup_scale if warmup_scale is not None else "",
        "sustain_scale": sustain_scale if sustain_scale is not None else "",
    }


def main() -> int:
    args = parse_args()
    selected_input = args.base_input or args.input
    input_path = selected_input if selected_input.is_absolute() else PROJECT_ROOT / selected_input
    output_path = args.output if args.output.is_absolute() else PROJECT_ROOT / args.output
    summary = build_sustained(
        input_path,
        output_path,
        args.period_sec,
        args.duration_sec,
        args.warmup_scale,
        args.sustain_scale,
        args.sampling_seed,
    )
    for key, value in summary.items():
        print(f"{key}: {value}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
